name: CI

on: [push]

jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write # only needed unless run with comment_mode: off
      contents: read       # only needed for private repository
      issues: read         # only needed for private repository    
    steps:
      - uses: actions/checkout@v3
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: Unit Test Results
          trx_files: "*.trx"
