name: CI

on: [push]

jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: Unit Test Results
          trx_files: "*.trx"
